### ISSUE TITLE
"Multiple widgets used the same GlobalKey"

### ISSUE THREAD

**Issue by rmoralesd** [bizz84/nested_navigation_examples#2]
In the example using "go_router", the app works as intended, but every time a change is made and a hot reload is triggered, the app crashes with "Multiple widgets used the same GlobalKey" exception.

**Comment by bizz84** [comment]
Seems the same issue as this: https://github.com/flutter/flutter/issues/113757

**Comment by tolo** [comment]
And the underlying issue is this: flutter/flutter#127206, i.e. GoRouter currently doesn't support inline creation of the GoRouter instance - it must be created only once and passed as a variable to MaterialApp.router.

**Comment by bizz84** [comment]
@tolo ah yes, that makes sense! Thank you very much for pointing it out!
